### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by nobogroup**
Removed librosa dependency by using scipy.io.wavfile.read.  Librosa commonly lags on dependencies and as none of their functions are needed best to remove it. 

Added a plot option that produces a twinx plot of time and rpm against revolutions.  

Added argparse args to support the plot:

plot_data yes/no
plot_title

### CODE REVIEW

**Comment by smcclem** [comment]
@nobogroup I looked at the github user and thought this was a bot, since it had no github activity.  Just looked at the branch name and recognized the initials.  

Please show the output here.  We'll need to update the README.md file, and include the a twinax plot.  That can go under images/

**Comment by nobogroup** [comment]
What output - the plot?

**Comment by smcclem** [comment]
> What output - the plot?

Yes. Just add the output to the images/ folder.  Then update the README and include the new usage and you can inline the image there.

**Comment by smcclem** [comment]
@nobogroup I wanted to add your plotting support when I had some free time, so I branched off yours and added the changes I requested.   In addition :

- I changed the command line option for plotting to just toggle plotting when the option is present. This is more consistent with most newer command line scripts. 
- By default it also writes a plot file out to the same directory as the input file. Could add more options for the output location at some point later if needed. 
- Checks to see if it can use plt.show() - not all envs can do that (mine included hence the file output)
- Added an alternating grey/white background to delineate each revolution on the plot. 

See:

https://github.com/smcclem/TurntableRPMAnalysis/tree/JPEnhancementsV1
https://github.com/smcclem/TurntableRPMAnalysis/blob/JPEnhancementsV1/README.md

I'd like to hear back from you before I merge this. Let me know what you think.

**Comment by nobogroup** [comment]
Can do but am in St. Maarten until Thursday so likely won't get a chance until I get back.

**Pull request merged**
